#!/bin/bash

set -e

PROD_DIR=/groups/dungeons/pipeline
LOCAL_DIR=$(git rev-parse --show-toplevel)

source "${LOCAL_DIR}/.githooks/update-venv"

if [[ "${PROD_DIR}" != "${LOCAL_DIR}" ]]; then
    echo "Static type checking (mypy)..."
    mypy
fi

echo "Linting (ruff)..."
ruff check "${LOCAL_DIR}"
echo "Formatting (ruff)..."
ruff format "${LOCAL_DIR}"
